apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-helloworls-rs


spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  templete:
    metadata:
      labels:
          app: myapp
    spec:
      containers:
      - name: myapp1
        image: kojibello/kojitechs-app:1.0.0
        ports: 
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata: 
  name: my-helloworld-service


spec:
  type: loadBalancer # i
  selector:
    app: myapp
  ports:
   - name: http
     port: 80
     targetPort: 80
